### PR TITLE
feat: get bundler ready to release

### PR DESCRIPTION
**Pull request by Souvikns**
**Description**

This PR aims to get bundler ready for publishing to NPM. Things this PR would do 
- [x] add correct installation string which is `npm install @asyncapi/bundler`
- [x] update the documentation with details about what bundler aims to solve and how it can help others. 
- [x] proper usage examples
- [x] Jsdoc API documentation

### CODE REVIEW

**Review by derberg — APPROVED** [review]
🚀 
just change to `feat` so we can trigger first official release

**Comment by Souvikns** [comment]
@derberg didn't we need to create a manual release for the first time?

**Comment by derberg** [comment]
oh, I was sure I did one already 🤔 

we also need to rename from `main` to `master` as we are not yet ready to have `main` as default branch 😞

**Comment by Souvikns** [comment]
> we also need to rename from main to master as we are not yet ready to have main as default branch 😞 

I created a branch [master](https://github.com/asyncapi/bundler/tree/master) but I think I don't have the rights to make it default 

> oh, I was sure I did one already 🤔 

don't see anything here https://www.npmjs.com/search?q=%40asyncapi%2Fbundler

**Review by derberg — APPROVED** [review]

**Pull request merged**
