### PR TITLE
chore: remove cli and refactor 

### PR DESCRIPTION
**Pull request by Souvikns**
**Description**
This PR aims to remove the CLI and set up different deployment steps and also update the license accordingly.

### CODE REVIEW

**Review by derberg — APPROVED** [review]
lgtm 🚀 
I think all in the configuration is correct

**Comment by Souvikns** [comment]
Do I need to update the title, I think chore will not trigger a build.

**Comment by derberg** [comment]
yea it won't, I just assumed it is not yet supposed to be released. We usually do not change package.json manually. Is all ready for the release?

**Comment by Souvikns** [comment]
This is my first time setting up semantic release, I have followed the configuration from diff, I will still double check it, also lets keep it chore only for now.

**Pull request merged**
