### PR TITLE
fix: tool file corrected

### PR DESCRIPTION
**Pull request by akshatnema**
**Description**
The .asyncapi-tool file is corrected according to the errors made while validating with the [schema](https://github.com/asyncapi/website/blob/master/scripts/tools/tools-schema.json).

### CODE REVIEW

**Comment by aeworxet** [comment]
This PR doesn't introduce a one property rename to simply align it's name with the existing [schema](https://github.com/asyncapi/website/blob/master/scripts/tools/tools-schema.json) like [PR #109](https://github.com/asyncapi/bundler/pull/109/files).
Phrase
```
If your code generator generates Python code, then specify Python, even if code
generator itself is written in JavaScript.
```
raised several questions:

- the Bundler is able to generate JSON, YAML and stringified JSON, even though it's written in TypeScript. Shouldn't JSON, YAML and stringified JSON be listed then?
- and, in this case, if some tool outputs result in several formats or languages, shouldn't there be introduced change to the [schema](https://github.com/asyncapi/website/blob/master/scripts/tools/tools-schema.json)
```
{
  "language": {
    "type": "array",
    "items": {
      "type": "string"
    }
  }
}
```
?
- how to denote 'stringified JSON' in the `.asyncapi-tool` at all?

@derberg @magicmatatjahu

(due to holiday season, answers might delay up to after ~Jan 10, 2023)

**Comment by akshatnema** [comment]
>If your code generator generates Python code, then specify Python, even if code
generator itself is written in JavaScript.

@aeworxet The `language` parameter inside `.asyncapi-tool` file doesn't specify the code generated by the generator. Rather, it specifies the primary language with which the generator has been made. And it was decided before that we will have a single primary language for each tool, which is majorly being used to build the tool. Hence, it is a string, not an array.

**Comment by aeworxet** [comment]
Even if there was a decision made, but change was forgotten to be introduced into the schema, the https://github.com/asyncapi/website/blob/master/scripts/tools/tools-schema.json currently still reads in the description of the `language` property
```
If your code generator generates Python code, then specify Python, even if code
generator itself is written in JavaScript.
```
so I have to hit the brakes on this PR until senior engineers come to any agreement.

**Comment by magicmatatjahu** [comment]
@akshatnema @aeworxet `language` refers to the language that you can use in the "runtime". That is, for generators it should be the language that the generator generates, but bundler even though it operates on YAML and JSON it does not mean that these are the target language, it's JS/TS because in this language it's written. It's a information if you can use given lib/script/api in your codebase :)

**Review by derberg — APPROVED** [review]
LGTM

`language` is for people to know if they can integrate it in their code or not

**Comment by aeworxet** [comment]
Should the description https://github.com/asyncapi/website/blob/master/scripts/tools/tools-schema.json be altered then? Made more clear maybe?

**Comment by magicmatatjahu** [comment]
@akshatnema Next time please use `chore:`

**Pull request merged**
