### PR TITLE
chore: add aeworxet as a codeowner

### PR DESCRIPTION
**Pull request by Souvikns**
**Description**

I think now we should add @aeworxet as a code owner to this project, @derberg I don't think we need tsc confirmation for this right?

### CODE REVIEW

**Comment by derberg** [comment]
@Souvikns no, it is up to the maintainers of the given repo to decide who becomes codeowner.

I think @aeworxet deserves it and also knows the project very well because he rewrote it to TS.

We just need him to agree 😄

**Comment by aeworxet** [comment]
Yes, I will take the codeownership.

**Review by derberg — APPROVED** [review]
Welcome aboard @aeworxet 
I invited you as a maintainer to this repo.

You also can become TSC member for entire initiative if you want

Just add your name to the list here https://github.com/asyncapi/community/blob/master/TSC_MEMBERS.json please

**Comment by derberg** [comment]
@Souvikns I changed PR title as even though I agree it is great @aeworxet is joining us, we do not need to release bundler 😄

**Comment by aeworxet** [comment]
@all-contributors please add @aeworxet for maintenance, review, ideas

**Pull request merged**
