### PR TITLE
fix: removed unwanted dependency

### LINKED ISSUE #114: Cleanup dependencies
I think `commander` and `meow` can be removed from the project as it no longer have CLI.

### PR DESCRIPTION
**Pull request by sambhavgupta0705**
**Description**

This PR removes the dependency commander and meow which were not in use.

**Related issue(s)**

Resolves #114

### CODE REVIEW

**Review by aeworxet — APPROVED** [review]

**Review by Souvikns — APPROVED** [review]

**Comment by aeworxet** [comment]
@all-contributors please add @sambhavgupta0705 for code

**Pull request merged**
